template-arb-file: app_es.arb
arb-dir: lib/localization
output-dir: lib/localization
output-localization-file: share_localizations.dart
output-class: ShareLocalizations
preferred-supported-locales: [es]
use-deferred-loading: false
synthetic-package: false
nullable-getters: true
